export const ACTIONTYPES = {
    ADD_LINEUP_PLAYER: "ADD_PLAYER",
    REMOVE_LINEUP_PLAYER: "REMOVE_LINEUP_PLAYER",
    TOGGLE_PLAYERS_COMPLETED: "TOGGLES_PLAYER_COMPLETED",
    ADD_SUBSTITUTES_PLAYER: "ADD_SUBSTITUTES_PLAYER",
    UPDATE_LINEUP_PLAYER_SUBMIN: "UPDATE_LINEUP_PLAYER_SUBMIN",
    HANDLE_CONFIRMATION_DONE: "HANDLE_CONFIRMATION_DONE",
    REMOVE_FROM_ALLPLAYER: "REMOVE_FROM_ALLPLAYER",
    ADD_TO_ALLPLAYER: "ADD_TO_ALLPLAYER",
    SET_PLAYERS_DATA: "SET_PLAYERS_DATA"
}
